name: termplux_engine_example
description: "Demonstrates how to use the termplux_engine plugin."
publish_to: 'none'
environment:
  sdk: '>=3.2.6 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  termplux_engine:
    path: ../
  flutter_boost:
    git:
      url: 'https://github.com/alibaba/flutter_boost.git'
      ref: '5.0.1'
  cupertino_icons: ^1.0.2
dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true