name: termplux_engine
description: "TermPlux Engine"
version: 0.0.1
publish_to: 'none'
environment:
  sdk: '>=3.2.6 <4.0.0'
  flutter: '>=3.3.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_ecosed:
    path: ../flutter_ecosed
  plugin_platform_interface: ^2.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  plugin:
    platforms:
      android:
        package: io.termplux.engine
        pluginClass: TermPluxEnginePlugin